name: AdvancedFlags
version: 1.1.3
main: me.mrxbox98.advancedflags.AdvancedFlags
authors: [ Mrxbox98 ]
description: Choose any flag to display over your head.
commands:
  af:
    description: Main AdvancedFlags command.