name: Feature Request
description: Request a feature
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. Mrxbox98#1482
    validations:
      required: false
  - type: textarea
    id: describe
    attributes:
      label: Describe the feature?
      description: Also tell us, what are the use cases?
      placeholder: Cool new feature!
      value: "I want it!"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/mrxbox98/AdvancedFlags/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true